# Generated by Django 4.2.2 on 2024-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_squashed_0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('PEND', 'In Progress'), ('DONE', 'Done')], default='To Do', max_length=20),
        ),
    ]
